I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day_1.rpy", line 848, in script
    jump d2_start
ScriptError: could not find label 'd2_start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day_1.rpy", line 848, in script
    jump d2_start
  File "/home/thatchedroof/Documents/renpy-7.4.8-sdk/renpy/ast.py", line 1752, in execute
    rv = renpy.game.script.lookup(target)
  File "/home/thatchedroof/Documents/renpy-7.4.8-sdk/renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'd2_start'.

Linux-5.11.0-37-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.4.8.1895
vs DeO 1.0
Mon Oct  4 21:31:32 2021
